set -e
true
true
/home/ramomar/miniconda3/bin/spades-core /home/ramomar/projects/assignment-2/spadee-assymbled/K21/configs/config.info /home/ramomar/projects/assignment-2/spadee-assymbled/K21/configs/isolate_mode.info
/home/ramomar/miniconda3/bin/spades-core /home/ramomar/projects/assignment-2/spadee-assymbled/K33/configs/config.info /home/ramomar/projects/assignment-2/spadee-assymbled/K33/configs/isolate_mode.info
/home/ramomar/miniconda3/bin/spades-core /home/ramomar/projects/assignment-2/spadee-assymbled/K55/configs/config.info /home/ramomar/projects/assignment-2/spadee-assymbled/K55/configs/isolate_mode.info
/home/ramomar/miniconda3/bin/spades-core /home/ramomar/projects/assignment-2/spadee-assymbled/K77/configs/config.info /home/ramomar/projects/assignment-2/spadee-assymbled/K77/configs/isolate_mode.info
/home/ramomar/miniconda3/bin/spades-core /home/ramomar/projects/assignment-2/spadee-assymbled/K99/configs/config.info /home/ramomar/projects/assignment-2/spadee-assymbled/K99/configs/isolate_mode.info
/home/ramomar/miniconda3/bin/spades-core /home/ramomar/projects/assignment-2/spadee-assymbled/K127/configs/config.info /home/ramomar/projects/assignment-2/spadee-assymbled/K127/configs/isolate_mode.info
/home/ramomar/miniconda3/bin/python /home/ramomar/miniconda3/share/spades/spades_pipeline/scripts/copy_files.py /home/ramomar/projects/assignment-2/spadee-assymbled/K127/before_rr.fasta /home/ramomar/projects/assignment-2/spadee-assymbled/before_rr.fasta /home/ramomar/projects/assignment-2/spadee-assymbled/K127/assembly_graph_after_simplification.gfa /home/ramomar/projects/assignment-2/spadee-assymbled/assembly_graph_after_simplification.gfa /home/ramomar/projects/assignment-2/spadee-assymbled/K127/final_contigs.fasta /home/ramomar/projects/assignment-2/spadee-assymbled/contigs.fasta /home/ramomar/projects/assignment-2/spadee-assymbled/K127/first_pe_contigs.fasta /home/ramomar/projects/assignment-2/spadee-assymbled/first_pe_contigs.fasta /home/ramomar/projects/assignment-2/spadee-assymbled/K127/strain_graph.gfa /home/ramomar/projects/assignment-2/spadee-assymbled/strain_graph.gfa /home/ramomar/projects/assignment-2/spadee-assymbled/K127/scaffolds.fasta /home/ramomar/projects/assignment-2/spadee-assymbled/scaffolds.fasta /home/ramomar/projects/assignment-2/spadee-assymbled/K127/scaffolds.paths /home/ramomar/projects/assignment-2/spadee-assymbled/scaffolds.paths /home/ramomar/projects/assignment-2/spadee-assymbled/K127/assembly_graph_with_scaffolds.gfa /home/ramomar/projects/assignment-2/spadee-assymbled/assembly_graph_with_scaffolds.gfa /home/ramomar/projects/assignment-2/spadee-assymbled/K127/assembly_graph.fastg /home/ramomar/projects/assignment-2/spadee-assymbled/assembly_graph.fastg /home/ramomar/projects/assignment-2/spadee-assymbled/K127/final_contigs.paths /home/ramomar/projects/assignment-2/spadee-assymbled/contigs.paths
true
/home/ramomar/miniconda3/bin/python /home/ramomar/miniconda3/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/ramomar/projects/assignment-2/spadee-assymbled/scaffolds.fasta --misc_dir /home/ramomar/projects/assignment-2/spadee-assymbled/misc --threshold_for_breaking_scaffolds 3
true
